### ISSUE TITLE
Online Map, Gray-Line setting

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#140]
When I enable Gray-Line in the "Online Map", the setting is lost when I restart QLog.

**Comment by foldynl** [comment]
Yeah, I know about the issue. Unfortunately, I don't know how to fix it. 

Briefly, all QLog maps run in the internal web browser and QLog acts as a server. But unfortunately, I don't have the knowledge how to get information back from the "browser" to QLog. I used this approach because it was very simple to use it  when you need just display data. But it starts to be problematic.

I will definitely leave this issue opened.
