### ISSUE TITLE
CW Keyer Error

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#194]
When my WinKeyer is not connected, this error message appears.

![Screenshot_20230413_110829](https://user-images.githubusercontent.com/26311402/231825946-9b993396-cdf8-4e4f-afaf-0a3e478c2c45.png)

I think that the text "No such file or directory" of the "Error Detail:" does not match the error. Presumably, the error message will refer to the keyer device.

**Comment by foldynl** [comment]
Please, could you provide more detail when it occurs? Does it occur when Keyer is not connected and you have assigned the Keyer to the Rig which is connected? Or when does it exactly occur? The Detail error is correct because you define a file that represents the device and this file does not exist if the device is not connected. But it is important to know when this error occurs.

**Comment by dl2ki** [comment]
The error occurred because the USB cable slipped out of the connector of the K3NG-Winkeyer yesterday, and I had not noticed it. If you now select "Equipment / Connect CW Keyer", the error message occurs.

The error message is okay from a technical point of view. Whether the user can do something with it is another question.

In this particular case, one could perhaps do without the detail line, as the problem with "Connectoon Error" is already described.  Or one could catch the error message and formulate the detail information for the pure user more understandably.

E.g. "CW-Keyer is not connected to QLog / PC", or similar.
