### ISSUE TITLE
Mode switch for ft857 is not active.

### ISSUE THREAD

**Issue by mppks** [foldynl/QLog#201]
The mode switch is not active in Rig Widget. 
![RigWidget](https://github.com/foldynl/QLog/assets/3379287/3da3f34b-9a70-41f5-9fdc-cbbb06326670)
![RigSettings](https://github.com/foldynl/QLog/assets/3379287/3381187f-dd8a-4809-983e-4a47f1273218)

**Comment by mppks** [comment]
1. Yes, it's Windows 10, I used the EXE-installer
2. Yes, the switch is empty if I define a rig for the first time.
   2.1 If I restart Qlog nothing changes - the mode switch is empty.
3. If I delete all rig profiles, restart Qlog and create a new one, for example, for icom-7300, then the switch is still empty.
4. If the rig is disconnected (combo is disabled) - the switch is empty.

![About](https://github.com/foldynl/QLog/assets/3379287/aaf7cb85-e2b8-438a-ad3a-da6dece4eadf)

**Comment by foldynl** [comment]
it is incomprehensible. I can't replicate this situation at all.

Can you please try another test. Run QLog with an input parameter ` -n test` (something like this: `qlog.exe -n test`)
This will cause qlog to start, but with a completely new database. Don't worry, you won't lose the original data, because if you run QLog again without a parameter, Qlog will return to the original database.

Once you have QLog running, fill in only the station profile in the initial settings and click OK. In this case, do you see "AM" in Rig Mode or not?

**Comment by mppks** [comment]
Rig mode - empty.
Below is a link to the video from the screen.
https://drive.google.com/file/d/10yiz_6FbL1VkwlIgOK9jwgrVfSqTb6et/view?usp=sharing

**Comment by foldynl** [comment]
Many thanks. The issue is confirmed. I can simulate it but I have to use Windows which is installed in Virtual Machine. That's very interesting.

**Comment by mppks** [comment]
The Modes are working. tnx 73!
