### ISSUE TITLE
Change global online map to English.

### ISSUE THREAD

**Issue by CutePotatoDev** [foldynl/QLog#238]
By some default OpenStreetMap shoving countries naming in local languages. It's nice but in most cases it's give some inconvenience. If possible jut make it English or may be switchable option.

**Comment by foldynl** [comment]
QLog depends on what openstreetmap provides, namely tile maps servers provide. The basic variant is the one you see. What I found out is that there are variants in German and French that Qlog uses if the Locale is set to DE or FR. I don't know of other language mutations. Therefore, unfortunately, I am not able to provide maps that will only be in English. If you know of a tile server that provides English-only maps, please let me know.

This issue was already discussed #180
