### ISSUE TITLE
QSO Detail / Edit dialog / "My Station"

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#252]
I have noticed that in the QSO Detail / Edit dialog in the "My Station" tab there is a field called "Operator Name", but it is empty.

![Screenshot_20231105_175941](https://github.com/foldynl/QLog/assets/26311402/8b78a312-1fd1-4b66-8f9b-0b0659ff02d6)
 

The field "Operator Name" is not available in the "My Station" tab in the main window.

![Screenshot_20231105_180025](https://github.com/foldynl/QLog/assets/26311402/16a9eab2-8493-4a32-8bbd-ddf9bc826250)

The operator name is already entered in the selected profile in "Settings / Profiles" and could therefore be displayed in the "QSO Detail / My Station" tab. 

![Screenshot_20231105_180117](https://github.com/foldynl/QLog/assets/26311402/2ba7958b-cbbe-407f-b577-048362cb5f07)

Is there a specific reason why the two "My Station" tabs have different content? But perhaps there is another consideration regarding the content of the tabs.

**Comment by foldynl** [comment]
>The field "Operator Name" is not available in the "My Station" tab in the main window.
> The operator name is already entered in the selected profile in "Settings / Profiles" and could therefore be displayed in the "QSO Detail / My Station" tab.

that's according to my proposal. The name and other parameters are defined by the profile and there is no need to display them.

But there is an issue that the QSO Detail Dialog does not show the name of the operator. This must be fixed.

> Is there a specific reason why the two "My Station" tabs have different content? But perhaps there is another consideration regarding the content of the tabs.

Yes. there is. As I wrote, QLog saves these parameters from profile. But if you want to change them later, there must be some way to do it. And that's why there is a different layout for QSO Detail, where you can modify the values independently of the profile.

**Comment by dl2ki** [comment]
OK, thank you. Then I can understand that.
