### ISSUE TITLE
Online Maps is black

### ISSUE THREAD

**Issue by foldynl** [foldynl/QLog#269]
Originally reported by @LU9DCE  in #267 

OS: Slackware 15.0
QLog is compiled from source code.

**Comment by filipmelik** [comment]
Hi, I would like to add to this bug report - when I open online map, the window is blank.

OS: macOS
QLog 0.32.0 downloaded as compiled dmg

**Comment by foldynl** [comment]
Hi Filip, unfortunately, I am not able to simulate this issue successfully and therefore it is not possible to fix it. It will be necessary to involve people who are affected to somehow find out why this is happening. 

QLog is tested on many platforms (Ubuntu 20.04, 22.04, Fedora, Flatpak, Windows 11) without any issue with online map. As you can see MacOS is not included in these platforms because I have no HW to run MacOS. MacOS builds are prepared via GitHub Actions

**Comment by foldynl** [comment]
If you can compile the QLog from source code then you can try this patch.
```
diff --git a/core/main.cpp b/core/main.cpp
index 6a56a84..389b9e7 100644
--- a/core/main.cpp
+++ b/core/main.cpp
@@ -348,6 +348,8 @@ int main(int argc, char* argv[])
     QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
 #endif
 
+    QCoreApplication::setAttribute(Qt::AA_UseSoftwareOpenGL);
+
 
     bool stylePresent = false;
```

**Comment by filipmelik** [comment]
I went through the hell and installed all the Qt toolchain to compile from source on macOS and I also needed to manually add links to hamlib and qtkeychain (this step is missing in the README, but I somehow distilled it from the instructions for other platforms). 

- the good news is, that the online map works now after manually compiling. 
- the bad news is, that it works even without the suggested patch - it was just built from cloned repo without any changes.

this is crop from the about window that was produced by manual build on my mac (I have Apple Silicon M1 mac - arm64).
<img width="209" alt="Screenshot 2024-02-22 at 15 00 10" src="https://github.com/foldynl/QLog/assets/5735485/ff3ced81-63c5-45c7-8cb1-f5dd173e7a19">

and this is crop from the qlog downloaded from release page:
<img width="210" alt="Screenshot 2024-02-22 at 15 02 24" src="https://github.com/foldynl/QLog/assets/5735485/28eaafea-cccb-4120-a16f-4545641352e9">

So only obvious difference is the Qt version and build arch. Since I am unfortunately not proficient with Qt and C++ by any means, I am not sure if I can tell what is going on 🤷

**Comment by foldynl** [comment]
Please, could you test a new [DMG](https://github.com/foldynl/QLog/releases/download/v0.32.0/QLog-0.32.0_MacOs14_dmg.zip)? The package was built by GitHub for Arm64 macOS 14.

I'm not sure if all the libraries are linked correctly. Unfortunately, homebrew for Apple Silicon has a different prefix so I had to change GitHub Build process.

**Comment by filipmelik** [comment]
Tried that, macOS unfortunately reports this file is damaged. This usually happens due to security settings, so I tried to turn off macOS Gatekeeper and run it again but the app crashed. Stack trace suggests there is a problem with code signature:

<img width="538" alt="Screenshot 2024-02-23 at 11 33 47" src="https://github.com/foldynl/QLog/assets/5735485/16f1d535-8ab5-4f0f-87b8-074db07aac19">

**Comment by foldynl** [comment]
Strange. I can't figure out what it means. If you are compiling QLog, you certainly have some experience. 

Can you please review the QLog [CI Actions](https://github.com/foldynl/QLog/blob/f2a0769a7af060125cb23f5c37250cdae6fa8e28/.github/workflows/c-cpp.yml#L58) for macOS?

**Comment by filipmelik** [comment]
First of all, I was an iOS developer, so macOS development is something I have only very faint knowledge about. I reviewed your changes in the CI Actions and run a few experiments here on my mac.  As far as I can see, the issue is really the codesigning. 

From what I have found on the net, it seems that **mac arm64 builds needs to be signed with identified developer's key**. The current qlog dmg is built using x86_64 architecture and it works, because it seems that x86_64 does not require codesigning as "new" arm64 builds do.
 
So this poses a unpleasant "problem" for OSS software. In order to get the signing certificate, you have to be enrolled in the Apple's developer program, which costs 99USD/year. 

[Here is some other HAM](https://forums.developer.apple.com/forums/thread/712555) asking how to proceed with codesigning and there could be probably a way how to do this without paying, but it will probably display security dialog to the end users 🤷 

This looks like something that needs further clarifications and especially - setup and coding 😬 . And the most important thing is, that we don't know whether this will actually help in the issue this thread was originally about 😂

**Comment by foldynl** [comment]
Many thanks for your research.

Probably, it's time to think about whether to continue with QLog on the MacOS platform.
