### ISSUE TITLE
Add setting for changing keyboard shortcuts

### ISSUE THREAD

**Issue by albertodiazsaez** [foldynl/QLog#293]
I don't think the Ctrl + S shortcut for saving a QSO is a good combination, when I'm a hunter I don't mind too much, but when I'm managing a pile-up it can be a bit uncomfortable. Most logging software uses "Enter" to save the QSOs, which I find much easy in the heat of a crowded pile-up.

So, instead of asking for this to be modified, I would like to be able to change the shortcuts avaiable in qLog to custom keys/key combinations, a new tab in the settings would be a nice option.

Using QLog 0.30.0 from Flatpak.

**Comment by foldynl** [comment]
I have modified the Enter functionality. Enter will be used to save the QSO, but only if

1) QSO is started (QSO Time is running)
2) Field RST(s/r) or field from row A or row B is focused
3) Focused field is not a Callsign, POTA, SOTA, WWFT

I will not implement a fully customized shortcut because it would generally not bring comfort for the users. It is necessary to think not only about the possibility of defining them, but also about the possibility that the given shortcut can affect other functionalities as well. How it happened in the case of Enter - for example if you press Enter in Callsign field, the current functionality sends a request to the online callbook and this functionality should remain as is. So it's not about implementing Enter as a save QSO button, but also thinking about secondary functions of the shortcut.

If you still have a problem with another shortcut, please let me know, because others may have a similar problem. Every request needs to be analyzed to see if it conflicts with these secondary functions.

**Comment by albertodiazsaez** [comment]
Oh! I did not realize that there was that feature with the enter key, and thanks for implementing the enter to save. One thing I think would be beneficial related to this (and if you want I'll open a new issue, and if not it doesn't matter) is a "Pile-up/expedition mode", in the form of a check-box, that makes Qlog to skip log search, save the contact directly with enter, and has always the clock ticking (so when a contact is saved, the moment it's saved is the real time of the contact).

**Comment by foldynl** [comment]
Perhaps there is a more elegant solution. The Online Callbook Search can be disabled through the `Settings`. I believe it would be beneficial if, in situations when the Online Callbook Search is disabled, pressing Enter could save the QSO. The only hesitation stems from the inability to determine whether an active online search is active or not. Initially, it may not be apparent to the operator what pressing Enter means in various situations. Introducing a checkbox is not an ideal solution since this function will not be frequently used. I will test an alternative approach.

**Comment by foldynl** [comment]
should be improved in 0.31
