### ISSUE TITLE
Problem importing QSOs

### ISSUE THREAD

**Issue by ea5wa** [foldynl/QLog#306]
I have this error message when trying to import some QSOs from an adif file

[QSO#1]: Error - Cannot insert to database - FOREIGN KEY constraint failed No es posible obtener la fila (21/01/2024; DP0POL; MFSK)
[QSO#2]: Error - Cannot insert to database - FOREIGN KEY constraint failed No es posible obtener la fila (21/01/2024; PY2PIM; MFSK)
[QSO#3]: Error - Cannot insert to database - FOREIGN KEY constraint failed No es posible obtener la fila (21/01/2024; EA4DFE; SSB)

Same adif file is correctly open with AdifMaster and uploaded to qrz.com without any error

**Comment by foldynl** [comment]
Please, could you send me the ADIF records for mentioned QSOs?

**Comment by ea5wa** [comment]
I tried to attached it here but is not allowed

**Comment by foldynl** [comment]
thanks for providing the ADIF file via email.

Unfortunately, your ADIF file contains many invalid fields. Some of them are critical, some are not critical for import.

Critical:
- `SWL` is defined as [boolean](https://adif.org/314/ADIF_314.htm#Boolean) in ADIF spec - should be `Y`, `y`, `N` or `n`. Your file contains `0`
- `QSO_RANDOM` is define also as boolean, your file contains `0`

there are many non-critical errors that do not meet the ADIF specification. Especially fields with `-1` like `MY_FISTS`, `K_INDEX`, `ITU_ZONE`, `MAX_BURSTS`, `SFI`, `TEN-TEN`, `UKSMG`. These fields must contain the positive integer value.

the last thing is the incomplete definition of mode. It does not beak ADIF, but it's quite unusual to define only the `Mode` and not the `submode`, especially in the case of MFSK, where there are several submodes - you probably should have FT4 submode there.

If you want to import the ADIF file to QLog then the minimum modification is  to change the field `SWL` and `QSO_RANDOM` from `0` to `N`. All non-critical error are accepted by QLog. Unfortunately, due to considerable freedom on the QLog import, these negative fields are saved with an incorrect value, so exporting these fields from Qlog will cause ADIF to violate some definitions again.

**Comment by ea5wa** [comment]
Hi Ladislav:

Thanks for the explanation

Same adif file is imported to other platforms (software) without any problem. Why?

73 de EA5WA Juan Carlos

**Comment by ea5wa** [comment]
Many thanks Ladislav

⁣73 de EA5WA Juan Carlos
