### ISSUE TITLE
ADIF export issue

### ISSUE THREAD

**Issue by ra3sad** [foldynl/QLog#316]
Hi!
There are problems with export in ADIF format - NAME and QTH fields are missing (but in table is not empty and looks fine), but if they exist - their contents are - `<qth:6>. ,  -` . This applies only to the Cyrillic characters. ADIF import with Cyrillic IS OK!
System charset is UTF-8. Debian 12. Software version - 0.31.0
Thanks, Alex.

**Comment by foldynl** [comment]
Alex, ADIF format has two formats - ADI and ADX. ADI is defined as pure ASCII format what means that there has not to be any non-ASCII character. On the other hand, ADX support UTF-8 charset. 

Because many applications do not comply with this, QLog is able to import UTF-8 fields even in the case of ADI. On the other hand, QLog never exports non-ASCII char to ADI. QLog tries to do some conversion, but in the ADI field, the non-ASCII char is always overwritten, as in your case.

If you want to export non-ASCII chars, then you need to use a more suitable format like ADX or CSV.

**Comment by ra3sad** [comment]
Thanks, I understand the logic. I solved the problem for myself by editing the source code. Maybe add a checkbox to export dialog to select whether to filter non-ASCII characters or not?

**Comment by foldynl** [comment]
checkbox is not a good idea, because it would totally disturb the consistency of the data in ADI. The only thing I could accept is a warning that such a conversion occurs.
