### ISSUE TITLE
Bandmap Issue

### ISSUE THREAD

**Issue by dl2ki** [foldynl/QLog#333]
Apparently there is a problem with the processing of the bandmap.

When clicking on the frequency, it is transferred to the Callsign field. When entering "DL" in the Callsign field, a purple line to the QSO partner appears in the online map, but the partner has not been entered completely. The same line appears when entering other callsigns or partial callsigns, e.g. "DL", "DB", "DC", "DD", "DE", or your own callsign. 

https://github.com/foldynl/QLog/assets/26311402/2ad48002-f8bc-4b1c-9630-654f83861be1

**Comment by foldynl** [comment]
Hi Wolfgang, your bandmap finding is an issue. It will be fixed. Your second finding is not an issue but it is a feature. If QLog is able to determine a country from a part of callsign then it shows  the purple line to the center of the country. it is implemented so that the operator knows approximately where the given country is located. I understand that this estimation is wrong for Germany or America (big countries), but I think it is useful in case of small countries. Currently it won't be fixed.

**Comment by dl2ki** [comment]
Many thanks for the information. I've learned something new again. However, I don't know why I didn't notice this earlier. This should then also apply to callsigns for which no QTH locator is stored. I'll have to try this out in more detail.

An alternative would be to display the line in a different color for this case, e.g. blue. From my point of view, however, you can also leave it as it is.
