### ISSUE TITLE
Rig/Rotor - Connect/Disconnect

### ISSUE THREAD

**Issue by DL2KI** [foldynl/QLog#53]
Since the rig/rotator is usually connected after starting QLog, it might be easier for operation to move the checkboxes from the "Equipment" menu to the 'Rig' / 'Rotator' widgets, or to place an additional checkbox or buttons here.

Example:

![Screenshot_20220429_194050_a](https://user-images.githubusercontent.com/26311402/165996811-2e64b0d6-4489-41fd-93f0-7e646d5c5001.png)

![Screenshot_20220429_194050_b](https://user-images.githubusercontent.com/26311402/165997439-f12e233f-5217-4abb-b5ff-ed2c4114b80c.png)

**Comment by foldynl** [comment]
I thought about whether to do it like you wrote. But in the end, I stayed with the solution that is now. And I'll tell you why. This is because I would like to keep the GUI as clear as possible. Connect / Disconnect is used very rarely, so I didn't want to add another button that won't actually be used.

When QLog becomes "more stable", then the shortcuts will be defined and I guess that connect is a hot candidate for it.

At this moment, I have no plan to implement the buttons for connect/disconnect as you show above.

**Comment by foldynl** [comment]
Basic shortcuts will be introduced in v0.9

**Comment by foldynl** [comment]
basic shortcuts via ALT + menu option in v0.9.0
