### ISSUE TITLE
Support for QT Styles

### ISSUE THREAD

**Issue by pulponair** [foldynl/QLog#88]
## Story
Starting QLog with the qt -style parameter seems to have no effect currently (Master branch as of today).
### Reproduce:
`qlog -style kvantum`
or 
`qlog -style Adwaita`
etc.

### Expected Result:
Qlog should start with the given style

### Actual Result:
Style is always Fusion

## Workarround
Comment hard coded fusion Style and rebuild
https://github.com/foldynl/QLog/blob/master/core/main.cpp#L236

## Solution
Check if style is set, if not use Fusion. I have no idea how to check the application style in QT otherwise i would file a PR. Sorry :|

**Comment by foldynl** [comment]
Excellent description.

I'll test it if it doesn't break something, but otherwise I don't see any problem to implement it.

**Comment by foldynl** [comment]
Unfortunately, It will not be added to the upcoming release v0.11(release scheduled for this or next week).  Despite the fact that this is a simple fix, for example Adwaita breaks the application dark mode setting (buttons are not displayed correctly). Therefore this change needs to be more tuned.

At this moment I leave the Fusion as a build-in style for v0.11 and will try to remove/improved it in next release.

**Comment by pulponair** [comment]
@foldynl 
No Problem.
I read through the documentation a little. And obviously setting the style before calling the constructor is the way to go.

>".. You can call [QApplication::setStyle](https://doc.qt.io/qt-5/qapplication.html#setStyle)() at any time, but by calling it before the constructor, you ensure that the user's preference, set using the -style command-line option, is respected..."
See: https://doc.qt.io/qt-5/qstyle.html#using-a-custom-style

So you probably want to add this at https://github.com/foldynl/QLog/blob/master/core/main.cpp#L230
`QApplication::setStyle(QStyleFactory::create("Fusion"));`

and remove this line https://github.com/foldynl/QLog/blob/master/core/main.cpp#L236

Regarding the dark mode switch. Yes i noticed that as well.

** Proposal: **
Don't display the dark mode switch if the Style is anything else but Fusion.
The dogma would than be:
Ship strong defaults, but leave the user the option to set his own preferences.

Agreed?

**Comment by pulponair** [comment]
@foldynl 
Yeah being a developer myself i totally see your point :).

Lets try to find a solution and argue a little - let me play the devils advocate :smiling_imp: 

QT offers the possibility to apply themes of the users choice to any Application. That is a fairly well known and widely used feature. There is even apps to centralize the theme management (e.g. kvantum). 

At the moment this feature is disabled in QLog by forcing the Fusion Theme. 

Using custom theme is not only a matter of the personal aesthetic taste but also a very important necessity for people that are e.g. visually disabled (color blindness, bad vision etc). Those people usually have a Vision friendly and high contrast Desktop theme. At the moment they can not apply that to qLog. 

Regarding the quality assurance Point: QT has guidelines how to use widgets and UI elemets in order to make them play along nicely with different themes. QT also has guidelines for Theme development.

So as log as the Qlog developer (you;) ) play along this guidelines you are totally not responsible for Bugs introduced by the Usage of a bad Theme (there is a lot of bad themes).

So for you nothing changes. You test with the default theme which is Fusion. That is it.

For the "Darkmode" switch: If it is only working Fusion, that this sounds like a bad smell to me because you are obviously relying on something "Fusion" specify (color palette maybe?).  

Maybe it is worth to reconsider the concept oft that switch? (can you point me to code of it?). 
Maybe one can introduce a "Dark mode" Color palette Setting defaulting to the Fusion dark mode colors?
Or still disable the Button with a a mouse over Tooltip saying "Switch only works with default theme" as an Interims solution?

Don't get me wrong i am trying to push something in i am just trying to find a solution :).

Last but not least, thank you for you work. 
I ve been using other loggers before and this is the best that far for me.
cqrlog -> pascal old, rubisch, unstabel
klog -> horrible instable

**Comment by foldynl** [comment]
Nikolas,

many thanks for you comment. I appreciate your opinion. You don't have to be the devils advocate. It is an open source, it is not the dictatorship of one programmer.

But let's go back to your comment.



> For the "Darkmode" switch: If it is only working in Fusion, then this sounds like a bad smell to me,
> Maybe it is worth to reconsider the concept oft that switch? (can you point me to code of it?).

You are right. I don't want to describe the details here, but considering that I wanted QLog to move quickly and it is not my original project - not all things are perfect. I do not fully understand some areas of Qt and the palette is one of them.

If QLog sets the dark mode then it calls this piece of code:
https://github.com/foldynl/QLog/blob/master/ui/MainWindow.cpp#L329

It seams that there is an issue when Adwaita is used. As I wrote above, the button color and button text color are very similar - therefore unreadable. Maybe it is something stupid that's why I wanted to take more time to understand it.

To be honest, there are a lot of problems with the introduction of dark mode (color icon for both environments and other things). So unfortunately at the moment it's really very sensitive to change color schema.

> Or still disable the Button with a a mouse over Tooltip saying "Switch only works with default theme" as an Interims solution?

I don't want to prepare a temporary solution.


> Don't get me wrong i am trying to push something in i am just trying to find a solution :).

that's fine. I have no problem with that - you are talking absolutely to the point.


> Last but not least, thank you for your great work.
> I ve been using other loggers before and this is the best that far for me.
> cqrlog -> pascal old, rubisch, unstabel
> klog -> horrible instable

I went the same way. 
CQRLog was fine but many probles with its architecture, obsoleted GUI framework etc. 
Klog - I tried to contribute, but the code was unreadable to me. I was lost.

Then I thought about which log I will use and found the deserted QLog (originally developed by DL2IC) . It was partly a function, it was a nice piece of code (I guess I messed it up a bit), but in the beginning it was very simple. So I tried to improve it.

**Comment by foldynl** [comment]
> Instead of adjusting the Colors for Fusion, choose a well known high quality darkmode them and use this.
> So you would have fusion for light and whatever for Dark.

That's make sense to me. I think that it is the best solution

**Comment by pulponair** [comment]
> That's make sense to me. I think that it is the best solution
Yes me too:). Let the design to the desgner, that takes a lot hazzle out of the code :)

But you still need to memorize whenever the user set his own theme, so in case he switches to dark and then back to light..

**Comment by foldynl** [comment]
to be honest, I get a little lost in styles. I have fully tested the kvantum style and I can say that it looks good. No issue found. 

On the other hand, Adwaita causes the total breakdown of several widgets - Especially spinboxes, QDateEdits, selected combos.

Do you know what this could cause? I read an issue report for Adwaita in their repo where your can find  issues from 2016 but it seems that they are already resolved.

See attached Statistic widget - it has quite easy layout but many issues can be found there
1) Combo Graph type - "QSO per" is too right, style does not reflect `layoutDirection` : `rightToLeft`
2) Date Ranges are totally undersized. 

Other widgets:
1) All spinboxes are undersized (especially when they have Size policy other than `expanding`)
2) and many other issue. 

![image](https://user-images.githubusercontent.com/942769/176413366-75aabe6f-a9a5-4bd8-ae8e-767fff35dd6c.png)

![image](https://user-images.githubusercontent.com/942769/176414463-eb0c30ff-c4e7-45fa-87c0-74b224ad544a.png)


As I wrote, there is no issue with kvantum. Is it possible that Adwaita is a not-so-tuned style?

in my opinion, I can't provide the user an option to change style when I know it is not working properly. The user will try the application (QLog) and will not solve if it is a style or application issue. Simply, it does not work therefore will not use in the future.

Yes, it is true that I can disclaim responsibility for other styles, but no one reads the warnings.

what is your opinion on it?

**Comment by foldynl** [comment]
> Regarding Adwaita itself: May be a problem of the the theme itself, but i can not say for sure. Could also be that the broken widgets are just not layouted correctly.

"Could also be that the broken widgets are just not layouted correctly." Maybe it is the core of problem, it's possible that I'm missing something, maybe the OS settings (Ubuntu 22.04). It is hard to say. I have tried several settings, but none is without issue in case of Adwaita. As I wrote, only the `expanding` size policy is more acceptable but Comboboxes have an issue as I show above. 

Look at my example below. It is an example of Setting Dialog. Very simple the Form Layout - no special setting of QDateEdit Widget - and result is

![image](https://user-images.githubusercontent.com/942769/176429335-1f2f42a7-fbc9-473c-82f7-62515ad33e2c.png)

> 
>     * Introduces an additional flag "expertMode" or "experimentalMode"

I would like to keep the options set to a minimum level. I don't like the style of N1MM and others, where you can set everything, but you are completely lost because you have no idea how exactly an option works and what all this has an impact on. The important thing is that you (as a developer) are not able to see all dependencies in such a large number of settings - as in Klog, where there is at least one setting that can break your log and the developers leave it as is (https://github.com/ea4k/klog/issues/304#issuecomment-870445848)

> 
>     * Add a fat disclaimer regarding the usage of this mode.

As I wrote, no one read the disclaimers.

I leave this issue opened, because I think it is important to support other styles. But in the upcoming releases Fusion will be a build-in style. We need to understand what the problem really is.

**Comment by pulponair** [comment]
@foldynl 
Ok i see.

I testet a little:
I Tryed the adwaita-qt port that ships with my Distribution (v1.41). I confirm the problem with this theme
I tryed the master branch of the adwaita-qt port (https://github.com/FedoraQt/adwaita-qt) as of today: same problem.
I tryed a couple of quantum themes, as well as plastique, cleanlooks -> all good there.

So i would assume it is a problem with the adwaita-qt port and i am gonna file an issue their and see what they respond.

Lets see what they respond.
